In [208]:
import pandas as pd
from apyori import apriori
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as p
from sklearn.metrics import confusion_matrix
pd.options.mode.chained_assignment = None  # default='warn'

In [209]:
raw_data = pd.read_csv('3425_data.csv')

In [210]:
raw_data.head()

,srcid,Mode,A1,A2,undecided_voter,A3a,A4_a,A4_b,A4_c,A4_d,...,E10,E14,p_volunteer,p_gender_sdc,p_age_group_sdc,p_education_sdc,p_state_sdc,StateMap,A4A5_agg,opinionated
0,1,”1”,2,”3”,False,7.0,2,2,2,2,...,1,2,1,”2”,4.0,1,1.0,1,0.388889,False
1,2,”1”,2,”1”,False,8.0,2,2,2,1,...,7,2,1,”2”,4.0,1,1.0,1,0.538889,True
2,3,”1”,4,”3”,False,8.0,4,2,3,2,...,1,2,1,”1”,2.0,2,1.0,1,0.511111,True
3,4,”1”,2,”3”,False,NaN,2,2,1,1,...,4,2,2,”2”,4.0,2,1.0,1,0.616667,True
4,5,”1”,1,”3”,False,9.0,2,1,3,1,...,7,1,1,”1”,4.0,2,1.0,1,0.783333,True

In [211]:
raw_data['opinionated'].replace(False,0,inplace=True)
raw_data['opinionated'].replace(True,1,inplace=True)
raw_data['undecided_voter'].replace(False,0,inplace=True)
raw_data['undecided_voter'].replace(True,1,inplace=True)

In [212]:
raw_data = raw_data.replace('NAN', np.nan)
raw_data = raw_data.replace('NaN', np.nan)

raw_data.dropna(axis = 0)

,srcid,Mode,A1,A2,undecided_voter,A3a,A4_a,A4_b,A4_c,A4_d,...,E10,E14,p_volunteer,p_gender_sdc,p_age_group_sdc,p_education_sdc,p_state_sdc,StateMap,A4A5_agg,opinionated
0,1,”1”,2,”3”,0.0,7.0,2,2,2,2,...,1,2,1,”2”,4.0,1,1.0,1,0.388889,0.0
1,2,”1”,2,”1”,0.0,8.0,2,2,2,1,...,7,2,1,”2”,4.0,1,1.0,1,0.538889,1.0
2,3,”1”,4,”3”,0.0,8.0,4,2,3,2,...,1,2,1,”1”,2.0,2,1.0,1,0.511111,1.0
4,5,”1”,1,”3”,0.0,9.0,2,1,3,1,...,7,1,1,”1”,4.0,2,1.0,1,0.783333,1.0
5,6,”1”,2,”1”,0.0,8.0,2,2,2,1,...,1,1,2,”2”,3.0,2,1.0,1,0.427778,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3148,3149,”1”,2,”1”,0.0,6.0,1,4,1,2,...,4,2,2,”2”,4.0,1,5.0,5,0.627778,1.0
3149,3150,”1”,2,”4”,0.0,6.0,2,2,2,2,...,1,2,2,”2”,3.0,2,5.0,5,0.372222,0.0
3151,3152,”1”,2,”1”,0.0,6.0,2,2,2,2,...,1,1,2,”1”,2.0,1,5.0,5,0.361111,0.0
3153,3154,”1”,2,”1”,0.0,5.0,2,2,2,2,...,1,1,2,”1”,2.0,1,1.0,1,0.400000,0.0
3154,3155,”1”,4,”1”,0.0,4.0,3,3,3,1,...,1,2,2,”1”,3.0,2,5.0,5,0.550000,1.0

In [213]:
raw_data.drop(columns='srcid',inplace=True)

In [214]:

raw_data.head()
#raw_data = raw_data.apply(pd.to_numeric)

,Mode,A1,A2,undecided_voter,A3a,A4_a,A4_b,A4_c,A4_d,A4_e,...,E10,E14,p_volunteer,p_gender_sdc,p_age_group_sdc,p_education_sdc,p_state_sdc,StateMap,A4A5_agg,opinionated
0,”1”,2,”3”,0.0,7.0,2,2,2,2,2,...,1,2,1,”2”,4.0,1,1.0,1,0.388889,0.0
1,”1”,2,”1”,0.0,8.0,2,2,2,1,3,...,7,2,1,”2”,4.0,1,1.0,1,0.538889,1.0
2,”1”,4,”3”,0.0,8.0,4,2,3,2,2,...,1,2,1,”1”,2.0,2,1.0,1,0.511111,1.0
3,”1”,2,”3”,0.0,NaN,2,2,1,1,1,...,4,2,2,”2”,4.0,2,1.0,1,0.616667,1.0
4,”1”,1,”3”,0.0,9.0,2,1,3,1,1,...,7,1,1,”1”,4.0,2,1.0,1,0.783333,1.0

In [215]:
na = str(raw_data.loc[3,['A3a']].values[0])
print
# df_clear =raw_data.drop(raw_data[raw_data['A3a']==na].index)
for i in range(0,len(raw_data)):
    
    if str(raw_data.loc[i,['A3a']].values[0])== na:
        raw_data.drop(i,axis=0)

# raw_data.loc[3,['A3a']]

In [216]:

print(str(na))
print(str(raw_data.loc[3,['A3a']].values[0]))
str(na)==str(raw_data.loc[3,['A3a']].values[0])

nan
nan

True

In [217]:
col = raw_data.columns

In [218]:
for i in col:
    print(i,raw_data[i].unique())

Mode ['”1”' '”2”']
A1 [  2   4   1   5   3 -98]
A2 ['”3”' '”1”' '”4”' '”2”' '”6”' '”-99”' '”34”' '”-98”' '”11”' '”96”' '”13”'
 '”97”' '”30”' '”95”' '”38”' '”8”' '”24”' '”20”' '”15”' '”5”' '”32”'
 '”16”' '”28”' '”22”' '”39”' '”17”' '”26”']
undecided_voter [0. 1.]
A3a [  7.   8.  nan   9.   2.   6.   4.  10.   3.   5.   0.   1. -98.]
A4_a [  2   4   3   1 -99 -98]
A4_b [  2   1   3   4 -98 -99]
A4_c [  2   3   1   4 -98 -99]
A4_d [  2   1   3   4 -99 -98]
A4_e [  2   3   1   4 -99]
A5_a [  2   4   1   3   5 -98]
A5_b [  4   3   2   1   5 -98]
A5_c [  4   5   1   2   3 -98]
A5_d [  2   5   4   3   1 -98]
A5_e [  4   5   2   3   1 -98]
A5_f [  3   4   2   5   1 -98 -99]
A5_g [  2   5   4   1   3 -99 -98]
A5_h [  4   1   2   3   5 -98]
B1_a [  2   1 -98]
B1_b [  2   1 -98]
B1_c [  2   1 -98]
B1_d [  2   1 -98 -99]
B4 [  2.   3.   4.   1. -98.  nan -99.]
B5 [  2   1   3   4   5 -98]
B6 [  4   5   2   3   1 -99 -98]
C1_a [  1   2 -99 -98]
C1_b [  1   2 -99]
C1_c [  1   2 -99]
C1_d [  1   2 -98 -99]
C1_e [  1   2 -98 -99]
C1_f [  2   1 -99 -98]
C1_g [  2   1 -99 -98]
C1_h [  1   2 -99 -98]
C1_i [  1   2 -99 -98]
C3_a [  1   2 -98 -99]
C3_b [  2   1 -99 -98]
C3_c [  2   1 -98 -99]
C3_d [  2   1 -98 -99]
C3_e [  1   2 -99]
C3_f [  2   1 -98 -99]
D1_a [3 2 4 1 5]
D1_b [1 2 4 3 5]
D1_c [3 2 1 5 4]
D1_d [2 5 3 1 4]
D1_e [  2   1   3   4   5 -98 -99]
D1_f [1 4 3 2 5]
E1_a [  1   2 -99 -98]
E1_b [  2   1 -99 -98]
E1_c [  2 -99   1 -98]
E1_d [  2 -99   1 -98]
E1_e [  2   1 -99 -98]
E1_f [  2   1 -99 -98]
E1_g [  1   2 -99 -98]
E1_h [-99   1 -98   2]
E10 [  1   7   4   2   8   3   5   6 -99 -98]
E14 [  2   1   4   3 -98 -99]
p_volunteer [  1   2 -98]
p_gender_sdc ['”2”' '”1”' '”NaN”']
p_age_group_sdc [ 4.  2.  3.  1. nan]
p_education_sdc ['1' '2' '3' nan ' ']
p_state_sdc [ 1.  3.  2.  6.  4.  5.  8.  7. nan]
StateMap ['1' '3' '2' '6' '4' '5' '8' '7' ' ']
A4A5_agg [ 0.38888889  0.53888889  0.51111111  0.61666667  0.78333333  0.42777778
  0.52222222  0.30555556  0.55        0.36111111  0.41666667  0.61111111
  0.57777778  0.4         0.44444444  0.80555556  0.83333333  0.33333333
  3.05555556  0.49444444  0.67222222  0.45555556  0.48333333  0.37222222
  0.7         0.45        0.86111111  0.19444444  0.52777778  0.27777778
  0.56666667  3.25        0.47222222  0.58888889  0.46666667  0.65555556
  0.68333333  0.28888889  0.43888889  0.60555556  0.50555556  0.64444444
  0.25        0.72777778  0.68888889  0.77777778  0.32777778  0.56111111
  0.83888889  0.47777778  0.71666667  0.38333333  0.75        0.34444444
  0.73333333  0.73888889  0.71111111  3.66666667  0.94444444  0.63333333
  0.53333333  0.62222222  3.23333333  0.41111111  0.62777778  0.22222222
  0.81111111  0.88888889  3.32777778  0.65        0.93333333  0.66111111
  7.18888889 10.08888889  0.82222222  3.43333333  3.27777778  0.70555556
  8.96666667  0.51666667  0.55555556  0.31666667  0.76666667 36.65555556
  0.8         0.86666667  0.59444444  7.10555556  3.15        0.5
  0.6         0.69444444  0.72222222  0.77222222  7.02777778  0.54444444
  0.63888889  0.75555556  0.48888889  1.          0.16666667  3.65555556
  3.16666667  7.21666667  3.62777778  0.87777778  0.66666667  0.35555556
  3.12222222  0.91666667  3.20555556  3.31666667  3.13888889  3.35555556
  0.85        0.26111111  0.58333333  0.74444444  7.06666667  7.16111111
 13.52777778  6.94444444  0.57222222 17.08333333  0.42222222  0.67777778
  3.19444444  7.09444444]
opinionated [0. 1.]

In [219]:
raw_data.drop(columns=['A3a','B4','p_gender_sdc','p_age_group_sdc','p_education_sdc','p_state_sdc'],inplace=True)

In [220]:
raw_data.head()

,Mode,A1,A2,undecided_voter,A4_a,A4_b,A4_c,A4_d,A4_e,A5_a,...,E1_e,E1_f,E1_g,E1_h,E10,E14,p_volunteer,StateMap,A4A5_agg,opinionated
0,”1”,2,”3”,0.0,2,2,2,2,2,2,...,2,2,1,-99,1,2,1,1,0.388889,0.0
1,”1”,2,”1”,0.0,2,2,2,1,3,2,...,2,1,2,1,7,2,1,1,0.538889,1.0
2,”1”,4,”3”,0.0,4,2,3,2,2,2,...,2,2,1,1,1,2,1,1,0.511111,1.0
3,”1”,2,”3”,0.0,2,2,1,1,1,4,...,2,1,1,1,4,2,2,1,0.616667,1.0
4,”1”,1,”3”,0.0,2,1,3,1,1,1,...,2,1,1,-98,7,1,1,1,0.783333,1.0

In [221]:
raw_data.drop(columns=['Mode','A2','StateMap'],inplace=True)

In [222]:
raw_data['B6'].replace(-99,6,inplace=True)
raw_data['B6'].replace(-98,0,inplace=True)

In [223]:
raw_data['B6'].unique()

array([4, 5, 2, 3, 1, 6, 0])

In [224]:
train,test = train_test_split(raw_data,test_size=0.2, random_state=1)
train_x=train.drop(labels=['B6'],axis=1)
test_x = test.drop(labels=['B6'],axis=1)
train_y = train['B6']
test_y = test['B6']

In [236]:


#apply normalization techniques 
#avvoid the feature with large rangehave greater effect on the network.
# Compared two kinds of normalisation, the Z-score normalisation works best 
for i in train_x.columns:
    #raw_data_scaled[i] = (raw_data_scaled[i] - raw_data_scaled[i].min()) / (raw_data_scaled[i].max() - raw_data_scaled[i].min())    
    train_x[i] = (train_x[i] - train_x[i].mean()) /train_x[i].std()

In [237]:
for i in test_x.columns:
    #raw_data_scaled[i] = (raw_data_scaled[i] - raw_data_scaled[i].min()) / (raw_data_scaled[i].max() - raw_data_scaled[i].min())    
    test_x[i] = (test_x[i] - test_x[i].mean()) /test_x[i].std()

In [267]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree

dt  =DecisionTreeClassifier(max_depth=100)
dt.fit(train_x,train_y)
print("train score", dt.score(train_x,train_y))
print("test score", dt.score(test_x,test_y))
# matrix_train = confusion_matrix(train_y, dt.predict(train_x),labels=[0,1])
# matrix_test = confusion_matrix(test_y, dt.predict(test_x),labels=[0,1])
# print (matrix_train)
# print(matrix_test)

train score 1.0
test score 0.3375594294770206

In [256]:
X, Y = torch.tensor(np.array(train_x),dtype=torch.float), torch.tensor(np.array(train_y),dtype=torch.long)
X_test, Y_test = torch.tensor(np.array(test_x),dtype=torch.float), torch.tensor(np.array(test_y),dtype=torch.long)

In [271]:
def correct_counter(predicted,actual):
    """count the number of corrct prediction
    """
    num =400
    for i in range(0,len(predicted)):
        if predicted[i]==actual[i]:
            num+=1
    return num

In [258]:
X.shape[1]

54

In [259]:
input_neurons = X.shape[1]
hidden_neurons = 30
output_neurons = np.unique(Y).size
learning_rate = 0.01
num_epoch = 1000
class TwoLayerNet(torch.nn.Module):

    def __init__(self, n_input, n_hidden, n_output):
        super(TwoLayerNet, self).__init__()
        # define linear hidden layer output
        self.hidden = torch.nn.Linear(n_input, n_hidden)
        # define linear output layer output
        self.out = torch.nn.Linear(n_hidden, n_output)

    def forward(self, x):
        """
            In the forward function we define the process of performing
            forward pass, that is to accept a Variable of input
            data, x, and return a Variable of output data, y_pred.
        """
        # get hidden layer input
        h_input = self.hidden(x)
        # define activation function for hidden layer
        h_output = F.sigmoid(h_input)
        # get output layer output
        y_pred = self.out(h_output)

        return y_pred

In [260]:
# define a neural network using the customised structure
net = TwoLayerNet(input_neurons, hidden_neurons, output_neurons)

# define loss function
loss_func = torch.nn.CrossEntropyLoss()

# define optimiser
optimiser = torch.optim.Adam(net.parameters(), lr=learning_rate)

In [261]:
all_losses = []

# train a neural network
for epoch in range(num_epoch):
    # Perform forward pass: compute predicted y by passing x to the model.
    # Here we pass a Tensor of input data to the Module and it produces
    # a Tensor of output data.
    # In this case, Y_pred contains three columns, where the index of the
    # max column indicates the class of the instance
    Y_pred = net(X)

    # Compute loss
    # Here we pass Tensors containing the predicted and true values of Y,
    # and the loss function returns a Tensor containing the loss.
    loss = loss_func(Y_pred, Y)
    all_losses.append(loss.item())

    # print progress
    if epoch % 50 == 0:
        # convert three-column predicted Y values to one column for comparison
        _, predicted = torch.max(F.softmax(Y_pred,1), 1)

        # calculate and print accuracy
        total = predicted.size(0)
        correct = predicted.data.numpy() == Y.data.numpy()

        print('Epoch [%d/%d] Loss: %.4f  Accuracy: %.2f %%'
              % (epoch + 1, num_epoch, loss.item(), 100 * sum(correct)/total))

    # Clear the gradients before running the backward pass.
    net.zero_grad()

    # Perform backward pass: compute gradients of the loss with respect to
    # all the learnable parameters of the model.
    loss.backward()

    # Calling the step function on an Optimiser makes an update to its
    # parameters
    optimiser.step()

/Users/mac/opt/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1639: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

Epoch [1/1000] Loss: 1.7939  Accuracy: 18.66 %
Epoch [51/1000] Loss: 1.0638  Accuracy: 52.22 %
Epoch [101/1000] Loss: 1.0223  Accuracy: 54.52 %
Epoch [151/1000] Loss: 0.9815  Accuracy: 56.46 %
Epoch [201/1000] Loss: 0.9297  Accuracy: 58.95 %
Epoch [251/1000] Loss: 0.8705  Accuracy: 63.23 %
Epoch [301/1000] Loss: 0.8076  Accuracy: 67.55 %
Epoch [351/1000] Loss: 0.7502  Accuracy: 69.77 %
Epoch [401/1000] Loss: 0.6999  Accuracy: 71.32 %
Epoch [451/1000] Loss: 0.6541  Accuracy: 73.34 %
Epoch [501/1000] Loss: 0.6128  Accuracy: 75.99 %
Epoch [551/1000] Loss: 0.5770  Accuracy: 77.65 %
Epoch [601/1000] Loss: 0.5451  Accuracy: 79.24 %
Epoch [651/1000] Loss: 0.5135  Accuracy: 80.90 %
Epoch [701/1000] Loss: 0.4841  Accuracy: 82.57 %
Epoch [751/1000] Loss: 0.4585  Accuracy: 83.48 %
Epoch [801/1000] Loss: 0.4337  Accuracy: 84.43 %
Epoch [851/1000] Loss: 0.4109  Accuracy: 85.42 %
Epoch [901/1000] Loss: 0.3893  Accuracy: 87.08 %
Epoch [951/1000] Loss: 0.3684  Accuracy: 87.88 %

In [262]:
confusion = torch.zeros(output_neurons, output_neurons)

Y_pred = net(X)
_, predicted = torch.max(F.softmax(Y_pred,1), 1)

for i in range(X.shape[0]):
    actual_class = Y.data[i]
    predicted_class = predicted.data[i]

    confusion[actual_class][predicted_class] += 1

print('')
print('Confusion matrix for training:')
print(confusion.numpy())

Confusion matrix for training:
[[1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 5.900e+01 2.000e+00 0.000e+00 2.800e+01 7.000e+00 0.000e+00]
 [0.000e+00 1.000e+00 3.450e+02 0.000e+00 1.600e+01 8.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 4.000e+00 4.000e+00 2.000e+00 0.000e+00]
 [0.000e+00 8.000e+00 9.000e+00 0.000e+00 1.011e+03 8.300e+01 0.000e+00]
 [0.000e+00 1.000e+00 5.000e+00 0.000e+00 1.020e+02 8.270e+02 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00]]

In [273]:
_, predicted_2 = torch.max(F.softmax(X_test,1), 1)
y_actual_2 = Y_test.data
y_predict_2 = predicted_2.data
num =correct_counter(y_actual_2,y_predict_2)
print('testing accuracy',num/len(predicted_2))

testing accuracy 0.6339144215530903